### ISSUE TITLE
Error when no FORMAT/GQ field in VCF

### ISSUE THREAD

**Issue by antonylebechec** [natir/variantplaner#12]
**Describe the bug**
Error if no FORMAT/GQ info

**To Reproduce**
1. VCF with no FORMAT/GQ
2. time variantplaner vcf2parquet -i example.vcf -v variants.parquet -g genotypes.parquet
3. Error
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/bin/variantplaner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/variantplaner/cli.py", line 105, in vcf2parquet
    genotypes_lf = extract.genotypes(lf, io.vcf.format2expr(vcf_header, input_path), format_string)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/variantplaner/extract.py", line 103, in genotypes
    [polars.col("value").arr.get(index).pipe(function=col2expr[col], name=col) for col, index in col_index.items()],  # type: ignore # noqa: PGH003
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/variantplaner/extract.py", line 103, in <listcomp>
    [polars.col("value").arr.get(index).pipe(function=col2expr[col], name=col) for col, index in col_index.items()],  # type: ignore # noqa: PGH003
KeyError: 'GQ'
```

**Expected behavior**
No error, and genotype.parquet with FORMAT fields within VCF. 
Mandatory fields (such as GQ for example), can be filled as None

**Screenshots**
Nope.

**System (please complete the following information):**
- `VariantPlanner` version: main
- Python version: 3.9
- OS: MacOS

**Additional context**

**Comment by natir** [comment]
As indicated in the `variantplaner vcf2parquet --help` help message all variants must have the same format field (lines that don't have this format are ignored) the default format field is `GT:AD:DP:GQ`, default values which can be discussed.

Command line you may use should look like:
```

**Comment by natir** [comment]
Just another point performance isn't yet the main target of project, so don't be very conclusive in your benchmark ?
