### ISSUE TITLE
variantplaner vcf2parquet "memory allocation of .. bytes failed" with the tutorial dataset

### ISSUE THREAD

**Issue by ehenrion** [natir/variantplaner#36]
Hi again @natir,

I tried to follow the VariantPlaner tutorial and fell into some issues with vcf2parquet.

The first one is actually more of a comment about the documentation : unless I a misunderstood something, I think you forgot to mention the mandatory `-c, --chrom2length-path` argument. ;)
Indeed, the tool does not run if this parameter is not provided.
I did fix this by providing the GRCh38 csv file from your repo : https://github.com/natir/variantplaner/blob/main/tests/data/grch38.92.csv

The other issue I had is described below. 

**Describe the bug**
 I had a memory allocation issue when running vcf2parquet when following the tutorial on https://github.com/natir/variantplaner/blob/main/docs/usage.md.

**To Reproduce**
1. Follow the tutorial on 'https://github.com/natir/variantplaner/blob/main/docs/usage.md' :
 - Dowload the test dataset.
 - Install VariantPlaner 0.2.2 with all the prerequisites.
  - Run command :
```
for vcf_path in $(ls vcf/*.vcf); do
     sample_name=$(basename ${vcf_path} .vcf);
     variantplaner -t 4 vcf2parquet -i ${vcf_path} -c grch38.92.csv
     -v variants/${sample_name}.parquet
     -g genotypes/samples/${sample_name}.parquet
     -f GT:PS:DP:ADALL:AD:GQ;
done
```
2. The error I got is :
```
memory allocation of 9006697177838592 bytes failed
Aborted (core dumped)
memory allocation of 9006239106121728 bytes failed
Aborted (core dumped)
memory allocation of 9006273723729920 bytes failed
Aborted (core dumped)
memory allocation of 9006499108427776 bytes failed
Aborted (core dumped)
memory allocation of 9006808411197440 bytes failed
Aborted (core dumped)
memory allocation of 9006194335070208 bytes failed
Aborted (core dumped)
```

**System:**
- VariantPlanner version: 0.2.2
- Python version: 3.10.4
- OS: Red Hat Enterprise Linux 8.8

Thanks for your support !

Edouard

**Comment by natir** [comment]
Hi @ehenrion,

I fix the usage page (not apply due to strange bug)

I'm sorry but I can't reproduce your bug, maybe could you try another version of python (3.11) ?

**Comment by ehenrion** [comment]
Hello @natir,

I just tried with Python 3.11 and it gave me the same error...
I will try on another system when I have the chance and will let you know.

May I asked what kind of configuration you're using during your tests ?
Thanks a lot !

Edouard

**Comment by natir** [comment]
Could make a test with last development version ?

```bash
pip install git+https://github.com/natir/variantplaner.git
```

**Comment by ehenrion** [comment]
I still have an error but not the same.
So I guess we are progresing, aren't we ? :) 
```
Traceback (most recent call last):
  File "/home/t1adm_al5v@/.local/bin/variantplaner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/variantplaner/cli.py", line 120, in vcf2parquet
    lf = io.vcf.into_lazyframe(input_path, chrom2length_path, extension=io.vcf.IntoLazyFrameExtension.MANAGE_SV)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/variantplaner/io/vcf.py", line 320, in into_lazyframe
    lf = lf.collect().select([col for col in lf.columns if col not in drop_column]).lazy()
         ^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/polars/utils/deprecation.py", line 96, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 1788, in collect
    return wrap_df(ldf.collect())
                   ^^^^^^^^^^^^^
polars.exceptions.ComputeError: strict conversion from `u64` to `u64` failed for column: real_pos, value(s) []; if you were trying to cast Utf8 to temporal dtypes, consider using `strptime`
```
Thanks so much for looking into this.
Edouard

**Comment by natir** [comment]
It's fix in last commit.

**Comment by ehenrion** [comment]
Error above has been fixed indeed.
And again, a new one has occured :
```
Traceback (most recent call last):
  File "/home/t1adm_al5v@/.local/bin/variantplaner", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/variantplaner/cli.py", line 122, in vcf2parquet
    extract.variants(lf).sink_parquet(variants)
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2031, in sink_parquet
    return lf.sink_parquet(
           ^^^^^^^^^^^^^^^^
OSError: No such file or directory (os error 2)
```

**Comment by natir** [comment]
Are you sure that `genotype/samples/` and `variants` directory exist?

**Comment by ehenrion** [comment]
Indeed !!!
I somehow skipped the `mkdir -p variants genotypes/samples/` command when following the tutorial.
Now all is working : I have my parquet files generated !!

Thank you Pierre :) 

Edouard

**Comment by natir** [comment]
Don't worry, I often forget too.

I'll have to see how to get a clearer error message.

**Comment by ehenrion** [comment]
Me again,

Sorry, I don't want to overload this thread, but I noticed that the `id` column is set to `null` in the parquet files.
```
[t1adm_al5v@BI0UAPPP007 vp_tuto]$ pqrs head variants/HG001.parquet
{id: null, chr: "chr1", pos: 783006, ref: "A", alt: "G"}
{id: null, chr: "chr1", pos: 783175, ref: "T", alt: "C"}
{id: null, chr: "chr1", pos: 784860, ref: "T", alt: "C"}
{id: null, chr: "chr1", pos: 785417, ref: "G", alt: "A"}
{id: null, chr: "chr1", pos: 797392, ref: "G", alt: "A"}
```
```
[t1adm_al5v@BI0UAPPP007 vp_tuto]$ pqrs head genotypes/samples/HG001.parquet
{id: null, sample: "HG001", gt: 2, ps: null, dp: 652, adall: [16, 234], ad: [0, 82], gq: 312}
{id: null, sample: "HG001", gt: 2, ps: null, dp: 639, adall: [0, 218], ad: [0, 84], gq: 194}
{id: null, sample: "HG001", gt: 2, ps: null, dp: 901, adall: [105, 406], ad: [0, 74], gq: 301}
{id: null, sample: "HG001", gt: 2, ps: null, dp: 820, adall: [125, 383], ad: [0, 70], gq: 339}
{id: null, sample: "HG001", gt: 1, ps: null, dp: 760, adall: [161, 142], ad: [25, 37], gq: 147}
```
When looking at the tutorial command results in the usage page, it seems that an `id` should have been set for all the records : 
```
pqrs head variants/samples/HG001.parquet
{id: 17886044532216650390, chr: 1, pos: 783006, ref: "A", alt: "G"}
{id: 7513336577790240873, chr: 1, pos: 783175, ref: "T", alt: "C"}
{id: 17987040642944149052, chr: 1, pos: 784860, ref: "T", alt: "C"}
{id: 10342734968077036194, chr: 1, pos: 785417, ref: "G", alt: "A"}
{id: 890514037559296207, chr: 1, pos: 797392, ref: "G", alt: "A"}
```

Is it something I should be worried about ?

**Comment by natir** [comment]
Yes, it's a mistake. The version of the documentation on the github pages is not up to date (a problem that will soon be corrected).

You need to delete the chr at the beginning of the chr in vcf columns:
https://github.com/natir/variantplaner/blob/main/docs/usage.md#download-data

**Comment by ehenrion** [comment]
Oh I see.
Thanks, will do !

**Comment by ehenrion** [comment]
Is it normal that the command 
```
mkdir -p genotypes/variants/
input=$(ls genotypes/samples/ | xargs -I {} -x echo "-i genotypes/samples/"{} | tr '\n' ' ')
variantplaner -t 8 struct $(echo $input) genotypes -p genotypes/variants/
```
creates the following output in the `genotypes/variants/` folder ?
```
[t1adm_al5v@BI0UAPPP007 vp_tuto]$ ll genotypes/variants/ | head -n20
total 0
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=0
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=1
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=10
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=100
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=101
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=102
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=103
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=104
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=105
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=106
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=107
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=108
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=109
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=11
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=110
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=111
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=112
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=113
drwxrwxrwx. 2 bi_cifs_bi0uappp007 domain users 0 Oct 24 17:01 id_part=114

```

**Comment by natir** [comment]
Yes
