### ISSUE TITLE
variantplaner annotations errors out with polars.exceptions.InvalidOperationError: sink_Parquet

### ISSUE THREAD

**Issue by ehenrion** [natir/variantplaner#37]
Good morning @natir,

I hope you don't end up hating me for creating all these issues...
But I have another one today...

**Describe the bug**
`polars.exceptions.InvalidOperationError: sink_Parquet` when running `variantplaner annotations` to convert vcf to parquet

**To Reproduce**
Follow the tutorial and reach the annotation section.
The commands to convert the annotations from vcf to parquet are throwing an error, but they also seem to work in a sense (i.e. they both produce parquet file with annotations) :
```
$ variantplaner -t 8 annotations -c grch38.92.csv -i variants.snpeff.vcf -o snpeff.parquet vcf -i ANN -r snpeff_id
2023-10-25 09:00:58,025 - annotations-vcf:ERROR:
Traceback (most recent call last):
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/variantplaner/cli.py", line 476, in annotations_vcf
    lf.sink_parquet(output_path)
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2031, in sink_parquet
    return lf.sink_parquet(
           ^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: sink_Parquet(ParquetWriteOptions { compression: Zstd(None), statistics: false, row_group_size: None, data_pagesize_limit: None, maintain_order: true }) not yet supported in standard engine. Use 'collect().write_parquet()'
```
```
$ variantplaner annotations -c grch38.92.csv -i annotations/clinvar.vcf -o annotations/clinvar.parquet vcf -r clinvar_id
2023-10-25 09:13:32,862 - annotations-vcf:ERROR:
Traceback (most recent call last):
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/variantplaner/cli.py", line 476, in annotations_vcf
    lf.sink_parquet(output_path)
  File "/home/t1adm_al5v@/.local/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2031, in sink_parquet
    return lf.sink_parquet(
           ^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: sink_Parquet(ParquetWriteOptions { compression: Zstd(None), statistics: false, row_group_size: None, data_pagesize_limit: None, maintain_order: true }) not yet supported in standard engine. Use 'collect().write_parquet()'
```

**System (please complete the following information):**
- VariantPlanner: 0.2.2-dev
- Python version: 3.11.1
- Red Hat Enterprise Linux: 8.8

**Comment by ehenrion** [comment]
OK thanks.

Time for me to play with real data then !
I will let you know how that goes :) 

Edouard
