### ISSUE TITLE
bug: polars.exceptions.ComputeError: Conversion from `i64` to `u16` failed 

### ISSUE THREAD

**Issue by ehenrion** [natir/variantplaner#41]
### Description of the bug
Trying to run variantplaner on my data (Homo_sapiens GRCh38) resulted in a polars casting error (that is at least what I think)

### To Reproduce
Decompress the vcf.gz file attached 
[2083096882_82307788_AHVF7TDSX7.vcf.gz](https://github.com/natir/variantplaner/files/13739497/2083096882_82307788_AHVF7TDSX7.vcf.gz)
 and run the following
     ```
     variantplaner -t 4 vcf2parquet
        -i 2083096882_82307788_AHVF7TDSX7.vcf
        -c grch38.92.csv
        -v variants/2083096882_82307788_AHVF7TDSX7.parquet
        -g genotypes/samples/2083096882_82307788_AHVF7TDSX7.parquet
        -f GT:AD:DP:GQ:PL
     ```

### Full traceback

<details><summary>Full traceback</summary>

```Traceback (most recent call last):
  File "/usr/local/bin/variantplaner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/variantplaner/cli.py", line 135, in vcf2parquet
    genotypes_lf.sink_parquet(genotypes, maintain_order=False)
  File "/usr/local/lib64/python3.9/site-packages/polars/lazyframe/frame.py", line 2031, in sink_parquet
    return lf.sink_parquet(
polars.exceptions.ComputeError: Conversion from `i64` to `u16` failed in column '' for 1 out of 15927 values: [103779]
```

</details>

### Expected behavior
After successfully following the variantplaner tutorial, I thought I was ready to run it on my data...
It seems though that the genotype format in the tutorial is not the same as mine. Could it be the source of the error ?

### Environment information
```
- __System__: Linux-4.18.0-513.9.1.el8_9.x86_64-x86_64-with-glibc2.28
- __Python__: cpython 3.9.18
- __Environment variables__:
- __Installed packages__:
  - `variantplaner` v0.2.3

```

**Comment by natir** [comment]
Thank you for reporting this issue. Sorry it's a mistake on my part, the vcf specification says that integer must be encoded on 32 bits and not 16.

This bug is fixed, version 0.2.4 integrates this correction.
