### ISSUE TITLE
bug: Genotype structuration error

### ISSUE THREAD

**Issue by ehenrion** [natir/variantplaner#42]
### Description of the bug

Genotype structuration by variants is failing

### To Reproduce

I followed the steps described in the tutorial using my own data and building the same file architecture i.e.
 ```
.
├── annotations
├── genotypes
│   ├── samples
│   └── variants
└── variants
```
Everything worked perfectly until the following :
```
mkdir -p genotypes/variants/
input=$(ls genotypes/samples/ | xargs -I {} -x echo "-i genotypes/samples/"{} | tr '\n' ' ')
variantplaner -t 8 struct $(echo $input) genotypes -p genotypes/variants/
```

### Full traceback

<details><summary>Full traceback</summary>

```python
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.9/site-packages/variantplaner/struct/genotypes.py", line 40, in __hive_worker
    lf = normalization.add_id_part(polars.concat(lf for lf in lfs if lf is not None))
  File "/usr/local/lib/python3.9/site-packages/variantplaner/normalization.py", line 84, in add_id_part
    return lf.with_columns(id_part=polars.col("id").variant_id.partition())  # type: ignore # noqa: PGH003
AttributeError: 'VariantId' object has no attribute 'partition'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/variantplaner", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/variantplaner/cli.py", line 390, in struct_genotypes
    struct.genotypes.hive(input_paths, prefix_path, threads=threads, file_per_thread=file_per_thread)
  File "/usr/local/lib/python3.9/site-packages/variantplaner/struct/genotypes.py", line 113, in hive
    pool.starmap(
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'VariantId' object has no attribute 'partition'
```

</details>

### Expected behavior

Spliting of the genotypes information in a hive like structure in the `genotpes/variants` folder

### Environment information

```bash
variantplaner --debug-info  # | xclip -selection clipboard
```
- __System__: Linux-4.18.0-513.9.1.el8_9.x86_64-x86_64-with-glibc2.28
- __Python__: cpython 3.9.18
- __Environment variables__:
- __Installed packages__:
  - `variantplaner` v0.2.4

**Comment by natir** [comment]
Hi,

Badly I can't reproduce your bug, are you sure you have 0.2.4 version of variantplaner.

Can you perform a full reinstall? (sorry for install time).

**Comment by ehenrion** [comment]
Hi,

Thanks for your answer.

It could be that my rust-toolset was broken/misinstalled...
I just started the re-installation of variantplaner 0.2.4 and will let you know how this goes.

**Comment by natir** [comment]
Just remove the last `/`

run:
```
mkdir -p genotypes/variants/
input=$(ls genotypes/samples/ | xargs -I {} -x echo "-i genotypes/samples/"{} | tr '\n' ' ')
variantplaner -t 8 struct $(echo $input) genotypes -p genotypes/variants
```

**Comment by ehenrion** [comment]
Hi @natir, 
Sorry for the delay in reply.

I tried removing the trailing `/` but it stills ends up with the same issue...

So I ran the command in verbose mode as the following :
```bash
variantplaner -t 8 -v -v -v -v struct $(echo $input) genotypes -p genotypes/variants 2> vp.errorlog
```
I also send you the `vp.errorlog` produced by the above command.

Looking at it, I wonder if this could come from my sample names : they all have `_` in their names.
As the sample names are used to build the path of the .parquet files, this could cause issues in `src/varinatplaner/struct/genotypes.py` when joining all paths by `_` :
```python
basenames = ["_".join(p.stem for p in g_paths if p is not None) for g_paths in path_groups]
```
--> variantplaner could be confused when trying to get each path back from `path_groups`, right ?

(I cand send you a smaller subset of data for more convenience if you wish)

On my end, I will try resetting my data lake with sample names without `_` in their name.

**Comment by ehenrion** [comment]
Nope, still the same error, even when having sample names without `_`...
I keep searching !

**Comment by ehenrion** [comment]
I think I spotted something.
Let me first explain what I did :
I cloned your mained branch, added some error message in `src/variantplaner/struct/genotypes.py`, line 46 :
```python
43    for name, df in lf.collect().group_by(polars.col("id_part")):
44         # required for python 3.11 and polars 0.20.4 wired
45         fix_name = name[0] if isinstance(name, tuple) else name
46         logging.error("trying to write : " + os.path.join(output_prefix, f"id_part={fix_name}", f"{basename}.parquet"))
47         df.write_parquet(output_prefix / f"id_part={fix_name}" / f"{basename}.parquet")
```
Then I reinstalled variantplaner and ran the command with only one sample (to minimize the size of the output) :
```bash
variantplaner -v -v -v -v -t 8 struct -i genotypes/samples/2081345853.parquet genotypes -p genotypes/variants
```
<details><summary>Traceback</summary>

```python
2024-01-17 12:43:00,026 - main:DEBUG: parameter: threads=8 verbose=4 debug_info=False
2024-01-17 12:43:00,028 - struct:DEBUG: parameter: input_paths=(PosixPath('genotypes/samples/2081345853.parquet'),)
2024-01-17 12:43:00,030 - struct.genotypes:DEBUG: parameter: prefix_path=PosixPath('genotypes/variants')
2024-01-17 12:43:00,030 - struct.genotypes:INFO: paths=(PosixPath('genotypes/samples/2081345853.parquet'),) output_prefix=PosixPath('genotypes/variants'), threads=4, file_per_thread=15
2024-01-17 12:43:00,205 - struct.genotypes:INFO: path_groups=[(PosixPath('genotypes/samples/2081345853.parquet'), None, None, None, None, None, None, None, None, None, None, None, None, None, None)], basenames=['2081345853']
ERROR:root:trying to write : genotypes/variants/id_part=15/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=111/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=22/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=34/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=0/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=49/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=31/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=140/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=155/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=117/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=36/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=156/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=159/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=63/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=12/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=141/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=43/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=84/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=25/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=78/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=138/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=143/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=7/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=108/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=99/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=46/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=42/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=87/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=135/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=75/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=144/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=57/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=18/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=114/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=152/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=54/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=123/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=48/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=9/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=93/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=27/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=1/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=4/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=45/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=40/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=37/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=153/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=81/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=58/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=3/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=21/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=126/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=33/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=137/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=149/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=134/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=19/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=39/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=129/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=164/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=120/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=51/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=52/2081345853.parquet
ERROR:root:trying to write : genotypes/variants/id_part=None/2081345853.parquet
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/variantplaner/struct/genotypes.py", line 47, in __hive_worker
    df.write_parquet(output_prefix / f"id_part={fix_name}" / f"{basename}.parquet")
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/polars/dataframe/frame.py", line 3496, in write_parquet
    self._df.write_parquet(
FileNotFoundError: No such file or directory (os error 2)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/variantplaner", line 8, in <module>
    sys.exit(main())
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/variantplaner/cli.py", line 390, in struct_genotypes
    struct.genotypes.hive(input_paths, prefix_path, threads=threads, file_per_thread=file_per_thread)
  File "/home/t1adm_al5v@/.local/lib/python3.9/site-packages/variantplaner/struct/genotypes.py", line 117, in hive
    pool.starmap(
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: No such file or directory (os error 2)
```
</details>

You can see that it tries to write in `genotypes/variants/id_part=None/2081345853.parquet` at one point.
But the folder `genotypes/variants/id_part=None` does not exists.

Is it supposed to create this `id_part=None` folder ?

**Comment by natir** [comment]
If variantplaner try to create an `id_part=None` flooder it's mean you have some variants with variants_id equal to None. 

Can you verify that this is the case (via pqrs or duckdb) if there are indeed variants_id with Null values. The chromosome is probably not present in the chromosome size csv file.

**Comment by ehenrion** [comment]
Indeed !

```python
>>> duckdb as db
>>> db.sql("SELECT * FROM read_parquet('/mnt/datagenetique/data/BIT/PRODUCTION/Databases/BMW/test/variants.parquet') WHERE id is NULL ORD
ER BY chr")
┌────────┬─────────┬───────────┬─────────┬─────────┐
│   id   │   chr   │    pos    │   ref   │   alt   │
│ uint64 │ varchar │  uint64   │ varchar │ varchar │
├────────┼─────────┼───────────┼─────────┼─────────┤
│   NULL │ 1       │  62577325 │ G       │ A       │
│   NULL │ 1       │ 160351691 │ C       │ T       │
│   NULL │ 1       │  26469248 │ G       │ A       │
│   NULL │ 1       │ 197146145 │ A       │ C       │
│   NULL │ 1       │   1756352 │ C       │ T       │
│   NULL │ 1       │ 161305670 │ T       │ G       │
│   NULL │ 1       │  68431531 │ G       │ T       │
│   NULL │ 1       │  43621160 │ C       │ T       │
│   NULL │ 1       │ 204245635 │ G       │ A       │
│   NULL │ 1       │ 207023129 │ C       │ T       │
│     ·  │ ·       │     ·     │ ·       │ ·       │
│     ·  │ ·       │     ·     │ ·       │ ·       │
│     ·  │ ·       │     ·     │ ·       │ ·       │
│   NULL │ 1       │ 173659397 │ C       │ G       │
│   NULL │ 1       │ 169710478 │ A       │ G       │
│   NULL │ 1       │  31756678 │ C       │ T       │
│   NULL │ 1       │  13308568 │ T       │ C       │
│   NULL │ 1       │  21850037 │ C       │ T       │
│   NULL │ 1       │ 111324762 │ G       │ T       │
│   NULL │ 1       │  21564093 │ C       │ T       │
│   NULL │ 1       │ 144439973 │ C       │ T       │
│   NULL │ 1       │  31432986 │ C       │ T       │
│   NULL │ 1       │  62475346 │ G       │ T       │
├────────┴─────────┴───────────┴─────────┴─────────┤
│ ? rows (>9999 rows, 20 shown)          5 columns │
└──────────────────────────────────────────────────┘
```

All in the chromosome 1, pretty odd...

Here is what my chorosome csv file looks like :

```bash
[t1adm_al5v@bi0uappp003 test]$ cat ../hg38.chrom.sizes.csv
1,248956422
10,133797422
11,135086622
12,133275309
13,114364328
14,107043718
15,101991189
16,90338345
17,83257441
18,80373285
19,58617616
2,242193529
20,64444167
21,46709983
22,50818468
3,198295559
4,190214555
5,181538259
6,170805979
7,159345973
8,145138636
9,138394717
MT,16569
X,156040895
Y,57227415
```

**Comment by natir** [comment]
Strange can you send me a sample of your data ?

**Comment by ehenrion** [comment]
Here it is : the vcf and parquet files of one single sample.

I had to add the `.txt` suffixe to ba able to attached them, so you may have to remove the suffixes before looking at them...
[2081345853.vcf.txt](https://github.com/natir/variantplaner/files/13963919/2081345853.vcf.txt)
[2081345853.parquet.txt](https://github.com/natir/variantplaner/files/13963937/2081345853.parquet.txt)

**Comment by ehenrion** [comment]
I got it !

Except for the alternative chromosomes, which are not in my chromosome csv file, the only difference was that my file didn't have the `chr,length` header.

I cannot explain why but once I added the header variantplaner stopped creating Null variant_ids !

In short, it now works ! :)

**Comment by ehenrion** [comment]
Now, what is the smartest way to use this genotype sructuration by variants ?
How do you determine which id_part a variant belongs to ?
 
Thanks

**Comment by natir** [comment]
I add an example in documentation https://natir.github.io/variantplaner/usage/#use-genotype-partition
